export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAILSED = "USER_LOGIN_FAILSED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_FAILSED = "USER_LOGOUT_FAILSED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_GET_ACCOUNT_REQUEST = "USER_GET_ACCOUNT_REQUEST";
export const USER_GET_ACCOUNT_SUCCESS = "USER_GET_ACCOUNT_SUCCESS";
export const USER_GET_ACCOUNT_FAILSED = "USER_GET_ACCOUNT_FAILSED";
